// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import Navbar from "../../components/NavBar";
import TestCRUD from "../../components/TestCRUD";
export default function Home() {
  return (
    <>
    <html>
      <body>
        <Navbar />
        <main className="container mx-auto p-6">
          <h1 className="text-3xl font-bold">Travel Guides</h1>
          <p className="mt-4">Tu espacio para guías mochileras.</p>
          <TestCRUD></TestCRUD>
        </main>
      </body>
    </html>
    </>
  )
}